version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: teller
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PGUSER: ${POSTGRES_USER}
      PGHOST: db
      PGDATABASE: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '1337:1337'
