name: daily-email
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send request
        run: |
          curl --request POST \
          --url 'https://teller.sh/api/daily'
